export const redirects = [
  ["/curseforge", "https://www.curseforge.com/minecraft/modpacks/fabulously-optimized"],
  ["/changelog", "https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#fabulously-optimized-changelog"],
  ["/discord", "https://discord.gg/fabulously-optimized-859124104644788234"],
  ["/github", "https://github.com/Fabulously-Optimized/fabulously-optimized"],
  ["/host", "https://www.bisecthosting.com/clients/aff.php?aff=2604"],
  ["/install", "https://wiki.download.fo/readme/install-instructions"],
  ["/issues", "https://github.com/Fabulously-Optimized/fabulosuly-optimized/issues"],
  ["/java", "https://adoptium.net/temurin/releases/?version=17&package=jre&arch=x64#version-filter"],
  ["/java17", "https://adoptium.net/temurin/releases/?version=17&package=jre&arch=x64#version-filter"],
  ["/java21", "https://adoptium.net/temurin/releases/?version=21&package=jre&arch=x64#version-filter"],
  ["/lego", "https://youtu.be/o-YBDTqX_ZU"],
  ["/mastodon", "https://floss.social/@fabulouslyoptimized"],
  ["/minecraft", "https://punktid.com/minecraft-java-bedrock?ref=robotkoer"],
  ["/modrinth", "https://modrinth.com/modpack/fabulously-optimized"],
  ["/mods", "https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/INCLUDED-MODS.md#included-mods"],
  ["/mrpack-to-zip", "https://fabulously-optimized.github.io/mrpack-to-zip/"],
  ["/rate", "https://alternativeto.net/software/fabulously-optimized/about/"],
  ["/terms", "https://wiki.download.fo/readme/disclaimers"],
  ["/translate", "https://wiki.download.fo/readme/language-support"],
  ["/thanks", "/contribute"],
  ["/update", "https://wiki.download.fo/readme/update-instructions"],
  ["/wiki", "https://wiki.download.fo"]
]
